### ISSUE TITLE
FilterSpecification type: missing "literal", etc.

### ISSUE THREAD

**Issue by cns-solutions-admin** [maplibre/maplibre-gl-js#1380]
2.2.0-pre.3:

The typescript type definition of FilterSpecification misses "literal".

It is not possible to define e.g.
* ["literal", false]

Additionally, according to the Doc. the following should be possible for match, but isn't:
* ["match", ["id"], [2, 3, 4], true, false]

As this worked in mapbox and in 1.5.x, I assume this is just a definition problem.

**Comment by HarelM** [comment]
The types are now generated from the code as opposed to how it was in 1.5,x (which was a different file manually generated).
It might be that the generated code/non generated code is not defined well.
Feel free to submit a PR that fixes this. :-)
You can take a look at the definition file in 1.5.x and see what's missing in the generated file now and try to understand what needs to be changed in the code.
If you need more info on which files to look into let me know.

**Comment by cns-solutions-admin** [comment]
Found the definition in build/generate-style-spec.ts, 
* from which src/style-spec/types.g.ts seems to be generated
* and somehow the maplibre-gl.d.ts in the final package?

On a second glance the whole definition is broken, e.g.
* ['==', string | FilterSpecification, FilterSpecificationInputType] et al. would not allow ['==', ['get', 'x'], ['get', 'y']]
* ["all", ...FilterSpecification[], FilterSpecificationInputType] et al.: no idea, why there is a FilterSpecificationInputType at the end
* according to the specification the filter is just an expression, so theoretically functions like "interpolate", etc. are also allowed
* etc.

The other questions are
* why isn't ExpressionSpecificationArray defined like that (+ missing functions)?
* why then isn't FilterExpression as ExpressionSpecificationArray or DataDrivenPropertyValueSpecification<boolean>?

BTW: after adding tests to src/style-spec/feature_filter.test.ts, it seems that the original problems (literal, match) still work in 2.2.

**Comment by HarelM** [comment]
The code hasn't changed (most of it), just the definitions, so the code it self should still work, in theory.
The code is generated from the style spec v8 file in some cases, and in other cases from different definitions.
These definition came from the code that was written in flow.
It very well might be that they are broken.
Feel free to try and fix them :-)
Any help there would be appreciated.
Note that these definitions are used in the code as well and it need to pass typescript transpillation, so the minimum (as it is now I guess) is that it passes it, but it probably not complete.

**Comment by cns-solutions-admin** [comment]
See PR #1383

**Comment by HarelM** [comment]
@cns-solutions-admin can you please help me with the following problem:
The types say the following is incorrect although I know it works and allows me to create a slope colored route in my app:
```ts
let colorStops = [0, "red", 0.5, "green", 1, "blue"];
compileTimeCheck([
    "interpolate",
    ["linear"],
    ["line-progress"],
    ...colorStops
]);
```
This fails with the following error:
```
 Type '["interpolate", ["linear"], ["line-progress"], ...(string | number)[]]' is not assignable to type '["interpolate", InterpolationSpecification, number | ExpressionSpecification, number | ExpressionSpecification, ExpressionSpecification | ExpressionInputType, ...(ExpressionSpecification | ExpressionInputType)[]]'.
    Source provides no match for required element
```

I tend to say the the extra tail the interpolate definition has seems redundant (the last `number | ExpressionSpecification, ExpressionInputType | ExpressionSpecification`, what do you think?

I just tried this version with my code and this failed there...

**Comment by cns-solutions-admin** [comment]
['interpolate', InterpolationSpecification, 
        number | ExpressionSpecification, // the number to find an interpolated value for
        number | ExpressionSpecification, ExpressionInputType | ExpressionSpecification, // at least one number and value
        ...(number | ExpressionInputType | ExpressionSpecification)[]] // more numbers and values

If you directly include the array values in the expression, it works flawlessly.
However, Typescript types the array colorStops as (number | string)[] instead of [number, string, number, string, number, string] and thus the number | string does not match with number | ExpressionSpecification (because of the string).

Removing the (at least one number and value) line from the specification would solve this problem.
But the typing would be less stringent and it would allow specs without stops, allow even the first stop to be specified as string, etc.
And if you tried to include a valueAndColorStops = [["line-progress"], 0, "red", 0.5, "green", 1, "blue"], it would still fail.

Maybe use a new type for the stops (it seems the spec. is still too lenient), e.g. 
```
StopsSpecification = [number, number | number[] | ColorSpecification] // shouldn't it be at least 2 stops?
  | [number, number | number[] | ColorSpecification, number, number | number[] | ColorSpecification]
  | [number, number | number[] | ColorSpecification, number, number | number[] | ColorSpecification, ...(number | number[] | ColorSpecification)[]];
...
['interpolate', InterpolationSpecification, number | ExpressionSpecification, ...StopsSpecification]
```
The the following would work:
```
let colorStops: StopsSpecification = [0, "red", 0.5, "green", 1, "blue"];
```

**Comment by HarelM** [comment]
Not sure I fully understand... Can you open a PR?

**Comment by hheexx** [comment]
I can't compile with this since 2.2.0

`'circle-color': [ 'step', ['get', 'point_count'], '#df2d43', 50, '#df2d43', 200, '#df2d43' ]`

 error TS2322: Type 'string' is not assignable to type 'number | ExpressionSpecification'.


(looks to me it's related to this)

**Comment by HarelM** [comment]
It is probably related.
Can you take a look at #1489 to see how I changed the typings to improve them and added a test to make sure it doesn't break in the future, and create a PR to fix this?

**Comment by hheexx** [comment]
Can you ship beta version to npm and I will check if it is fixed? I don't have time currently.

**Comment by HarelM** [comment]
Latest version is on npm - 2.3.1-pre something...

**Comment by hheexx** [comment]
It's broken in that version

**Comment by HarelM** [comment]
You can use 2.1.9

**Comment by hheexx** [comment]
Yes I use that

**Comment by cns-solutions-admin** [comment]
See #1510: fixed typing of interpolate to allow number[], but no expressions, as described in https://github.com/maplibre/maplibre-gl-js/issues/1380#issuecomment-1212845168

**Comment by HarelM** [comment]
Thanks!!
