### ISSUE TITLE
maplibre-gl.d.ts Syntax Error when using strict

### ISSUE THREAD

**Issue by narvarjosh** [maplibre/maplibre-gl-js#790]
I just started trying to use `maplibre-gl` today, and was following along with this conversation because I was unsuccessful in compiling types: https://github.com/maplibre/maplibre-gl-js/pull/787. After seeing this resolved and `v2.0.2` published, I tried it myself but still am getting errors.

**maplibre-gl-js version**: v2.0.2

**browser**: N/A

### Steps to Trigger Behavior

 1. Include and import `"maplibre-gl": "2.0.2"`
 2. Compile types

### Expected Behavior
Types compile

### Actual Behavior
There is a syntax error in the types output:
```
import type Pbf from 'pbf';
```
leading to the following errors:
```
../../node_modules/maplibre-gl/dist/maplibre-gl.d.ts:1:17 - error TS1005: '=' expected.

1     import type Pbf from 'pbf';
                  ~~~

../../node_modules/maplibre-gl/dist/maplibre-gl.d.ts:1:21 - error TS1005: ';' expected.

1     import type Pbf from 'pbf';
                      ~~~~

../../node_modules/maplibre-gl/dist/maplibre-gl.d.ts:1:26 - error TS1005: ';' expected.

1     import type Pbf from 'pbf';
                           ~~~~~
```

**Comment by wipfli** [comment]
Thanks for reporting. My [debugging test repo](https://github.com/wipfli/maplibre-typescript/runs/4859914957?check_suite_focus=true) shows the same error with v2.0.2:

```
Error: node_modules/maplibre-gl/dist/maplibre-gl.d.ts(1,17): error TS1259: Module '"/home/runner/work/maplibre-typescript/maplibre-typescript/node_modules/@types/pbf/index"' can only be default-imported using the 'esModuleInterop' flag
Error: node_modules/maplibre-gl/dist/maplibre-gl.d.ts(20,53): error TS2503: Cannot find namespace 'GeoJSON'.
```

**Comment by HarelM** [comment]
See if you can reproduce it in stackblitz.
It might be that you'll need a newer version of typescript...?

**Comment by narvarjosh** [comment]
@HarelM Thanks for the suggestion! I do see it appears we would need a newer version of typescript. We're at `3.7.7`, and the syntax it's breaking on was added in `3.8`: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export.

I appreciate both your help.

**Comment by HarelM** [comment]
No problem.
I'm still interested to know if someone was able to use version 2, with typescript and react/angular.
I'm trying to use it in my app but seems that is not smooth... :-/

**Comment by wipfli** [comment]
https://stackoverflow.com/questions/56238356/understanding-esmoduleinterop-in-tsconfig-file

**Comment by wipfli** [comment]
I reopen because the errors I saw remain.

**Comment by HarelM** [comment]
I think you need to add the flags described in the SO question.
Also you probably need to install @type/geojson - we should probably move this from devDependencies to dependencies like I did for pbf. 
I've just upgraded my project to use maplibre 2.0.2 and I don't have compilation issues.
But feel free to fix this :-)

**Comment by hheexx** [comment]
@HarelM  I have errors in angular also. Typescript 4.4

Error: node_modules/maplibre-gl/dist/maplibre-gl.d.ts:1:17 - error TS1259: Module '"/home/hex/xxx/ClientApp/node_modules/@types/pbf/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

1     import type Pbf from 'pbf';
                  ~~~

  node_modules/@types/pbf/index.d.ts:82:1
    82 export = Pbf;
       ~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

**Comment by HarelM** [comment]
Does adding this flag in tsconfig solves the issue?

**Comment by hheexx** [comment]
@HarelM skipLibCheck?   Yes, but then we are at same place as 2.0.1 :)

**Comment by hheexx** [comment]
aha... allowSyntheticDefaultImports. Will try....

**Comment by wipfli** [comment]
I wanted to make a stackblitz to reproduce these errors, but everything looks OK in this MapLibre GL JS v2.0.2 + React + TypeScript example: https://stackblitz.com/edit/react-starter-typescript-qrj3qw?file=index.tsx

**Comment by HarelM** [comment]
Yup. I believe the types are good.

**Comment by ThibaudM** [comment]
I have tried to use the v2.0.2 dts file in the map-gl-indoor project (https://github.com/map-gl-indoor/map-gl-indoor/tree/feat/maplibre) but also encountered three TS errors.
```shell
> dts-bundle-generator -o dist/map-gl-indoor.d.ts src/index.ts
Compiling input files...
Processing src/index.ts
Writing src/index.ts -> dist/map-gl-indoor.d.ts
Checking generated files...
Compiler option "skipLibCheck" is disabled to properly check generated output
node_modules/maplibre-gl/dist/maplibre-gl.d.ts(2430,61): error TS2344: Type 'Us' does not satisfy the constraint '{}'.
  Type 'unknown' is not assignable to type '{}'.
node_modules/maplibre-gl/dist/maplibre-gl.d.ts(8797,4): error TS2411: Property 'mousemove' of type 'undefined' is not assignable to 'string' index type '(e: any) => void'.
node_modules/maplibre-gl/dist/maplibre-gl.d.ts(8798,4): error TS2411: Property 'mouseout' of type 'undefined' is not assignable to 'string' index type '(e: any) => void'.

Error: Compiled with errors
```
Unfortunately, `skipLibCheck` cannot be used as a workaround here.
**typescript version:** 4.5.2

Let me know if you prefer I open another issue
Similar errors found here: #474

**Comment by HarelM** [comment]
You can check out if #800 solves this, not sure, I'm not entirely sure what the problem is.
The definition file is correct as far as I know and understand.

**Comment by wipfli** [comment]
```
Error: node_modules/maplibre-gl/dist/maplibre-gl.d.ts(3,8): error TS1259: Module '"/home/runner/work/maplibre-typescript/maplibre-typescript/node_modules/@types/mapbox__point-geometry/index"' can only be default-imported using the 'esModuleInterop' flag
```
was produced with v2.0.4 and a minimal TypeScript `app.ts` which reads:

```ts
import maplibregl from "maplibre-gl";
```

See [workflow run](https://github.com/wipfli/maplibre-typescript/runs/4913199673?check_suite_focus=true) in https://github.com/wipfli/maplibre-typescript

**Comment by HarelM** [comment]
@wipfli can you try and add the `esModuleInterop` flag?

**Comment by wipfli** [comment]
This flag did not solve the problem for me.

**Comment by ThibaudM** [comment]
> You can check out if #800 solves this, not sure, I'm not entirely sure what the problem is. The definition file is correct as far as I know and understand.

It does not work with #800 :(

The #800 added me these errors:
```shell
node_modules/maplibre-gl/dist/maplibre-gl.d.ts(3,19): error TS7016: Could not find a declaration file for module '@mapbox/point-geometry'. '[...]/map-gl-indoor/node_modules/@mapbox/point-geometry/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/mapbox__point-geometry` if it exists or add a new declaration (.d.ts) file containing `declare module '@mapbox/point-geometry';`
node_modules/maplibre-gl/dist/maplibre-gl.d.ts(5,52): error TS7016: Could not find a declaration file for module '@mapbox/vector-tile'. '[...]/map-gl-indoor/node_modules/@mapbox/vector-tile/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/mapbox__vector-tile` if it exists or add a new declaration (.d.ts) file containing `declare module '@mapbox/vector-tile';`
```
that can be fixed following the tips, but the three previous remain.

**Comment by HarelM** [comment]
Please install latest version, I think this is now solved.

**Comment by ThibaudM** [comment]
If the latest version is 2.1.1, it is the version which [the one I am testing right now](https://github.com/map-gl-indoor/map-gl-indoor/pull/12) for `map-gl-indoor`:
https://github.com/map-gl-indoor/map-gl-indoor/blob/feat/maplibre/package.json#L55
Errors from GitHub actions are the same as my local ones:
https://github.com/map-gl-indoor/map-gl-indoor/runs/5003560452?check_suite_focus=true

**Comment by HarelM** [comment]
Bummer :-(
No clue what this error is and what causes this.
I've integrated `dts-bundle-generator` into this library to create the d.ts file as well, but since the library is compile to UMD and is compiling both worker code and browser code the generator has some issues with it so I can't use it without `--no-check`.
But when I'm generating the file I don't receive these errors.
I'd be happy to review a PR that solves this, but I honestly don't have a clue what's causing this.
The author of `dts-bundle-generator` helped me a lot to overcome most of the error I had, maybe he can help here as well.
See the following issue for my correspondence:
https://github.com/timocov/dts-bundle-generator/issues/175

**Comment by FVilli** [comment]
I'm trying to use map libre in a simple angular/ionic web app; 
https://documentation.maptiler.com/hc/en-us/articles/4411342514193-How-to-display-a-map-in-Angular-using-MapLibre-GL-JS

I've got this error: maplibre-gl.js:31 Error {message: 'mismatched image size'}

**Comment by HarelM** [comment]
I don't this this is the same issue as described here, instead, I think this was solved by #718.
I'm using maplibre with ngx-maplibre-gl fir angular/ionic/cordova BTW...

**Comment by dmolinet-nexus** [comment]
Is there a wat to get this working with angular@8 and typescript@3.5.3?
I already added `"esModuleInterop": true` but that did not work.
Any help please?

**Comment by HarelM** [comment]
I don't know about angular 8 as it's pretty old, I'm using angular 13 and was using angular 12 up until recently and I have this working in the following repo:
https://github.com/IsraelHikingMap/Site/tree/main/IsraelHiking.Web

**Comment by HarelM** [comment]
Try installing @types/pbf for the above error. Latest version of maplibre has this as a dependency to resolve this missing types issues I believe.

**Comment by dmolinet-nexus** [comment]
I already have `"@types/pbf": "3.0.2"` as a dev dependency.
And I'm trying to get v2.0.2 working because other 2.X.X versions throw a lot of other typescript errors.

**Comment by HarelM** [comment]
Well, sorry I'm unable to help. If you think there's something in the d.ts file that is generated while building this code please submit a PR, I have a problem reproducing this on my side...

**Comment by timber-they** [comment]
Somehow I'm still getting this error in the latest (`3.6.2`) version, with Angular `17.0.4` and typescript `5.2.2`:
```
Error: node_modules/maplibre-gl/dist/maplibre-gl.d.ts:3:8 - error TS1259: Module '"/.../node_modules/@types/mapbox__point-geometry/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

3 import Point from '@mapbox/point-geometry';
         ~~~~~

  node_modules/@types/mapbox__point-geometry/index.d.ts:40:1
    40 export = Point;
       ~~~~~~~~~~~~~~~
    This module is declared with 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
```
Adding the flags `esModuleInterop` and / or `allowSyntheticDefaultImports` in my `tsconfig.json` also didn't help, because that caused other compilation errors in my project. Is this still the same or a new error as the one described in this issue?

**Comment by HarelM** [comment]
We have added a test to see that the typings we provide are strict.
I'm pretty sure it's still checks that.
But I might be wrong.
Try reproducing this on a clean setup.

**Comment by timber-they** [comment]
@HarelM well actually I can't reproduce it in a clean setup. Any ideas on how to narrow the actual problem down then?

**Comment by timber-they** [comment]
@HarelM it doesn't seem to be trivial to reproduce the error on a clean setup, because I can't get npm to generate the relevant files which in the actual environment provoke the error. I might also not be the best person for the job, because I don't know my way around either angular / node / ..., nor maplibre (yet). Maybe you can trust me that this issue appears in newer versions, but not in version 1.x and rather try to work with the error message I got? Because the error message quite clearly seems to indicate that there's something wrong with `maplibre-gl`.

If you want to check out the code that's currently producing the error, the project is [open source](https://github.com/mint-o-badges/badgr-ui/tree/ui_update_dependencies) (in the committed version, maplibre is still on version 1.15.3, thus it compiles and works). I can also create a new issue for this bug, if that's the appropriate behavior. Please let me know if I can assist with any further information. Other than that, I'd be quite happy about a workaround, because right now we seem to be forced to continue using the 1.x version.

**Comment by HarelM** [comment]
The linked branch doesn't build for me on code spaces using `nvm install && npm install && npm run build`.
There is a huge difference between maplibre 1.15 and the current version. Also if you are using angular I suggest to use `ngx-maplibre-gl`.
Bottom line, you'll need to overcome it yourself... I assure you that the latest version is working as expected in an angular environment.

**Comment by neodescis** [comment]
Also, I would note that imports like these in typing files produced with `esModuleInterop: true` and `esModuleInterop: false` seem to be mutually incompatible. Or at least that has been my experience, unfortunately.
